import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const lekton = localFont({
  src: "../public/fonts/Lekton-Bold.ttf",
  variable: "--lekton",
  weight: "bold",
});
const koulen = localFont({
  src: "../public/fonts/Koulen-Regular.ttf",
  variable: "--koulen",
  weight: "400",
});
const inter = localFont({
  src: "../public/fonts/Inter.ttf",
  variable: "--inter",
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lekton.variable} ${koulen.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
